from aim_fsm import *

class CheckForRobot(StateNode):
    def start(self, event=None):
        super().start(event)

        closest = None
        min_dist = float('inf')

        for obj in self.world_map.objects.values():
            if isinstance(obj, RobotObj) and obj.is_visible:
                dx = obj.pose.x - self.robot.pose.x
                dy = obj.pose.y - self.robot.pose.y
                dist = (dx**2 + dy**2)**0.5

                if dist < min_dist:
                    min_dist = dist
                    closest = obj

        if closest is None:
            self.post_failure()
            return

        print("Robot detected: ", closest)
        print("Distance: ", min_dist)
        self.robot.nearby_robot = closest

        self.post_success()

class ReplanPath(StateNode):
    def start(self, event=None):
        super().start(event)
    
        print("Robot obstacle detected.")
        print("Robot registered as an RRT obstacle.")
        print("Path plans should route around it.")

        self.post_completion()

class AvoidRobot(StateMachineProgram):
    def setup(self):
        #         detect: CheckForRobot()
        #         detect =S=> replan
        #         detect =F=> done
        # 
        #         replan: ReplanPath()
        #         replan =C=> done
        # 
        #         done: Say("Path update")
        
        # Code generated by genfsm on Mon Jun  8 13:45:51 2026:
        
        detect = CheckForRobot() .set_name("detect") .set_parent(self)
        replan = ReplanPath() .set_name("replan") .set_parent(self)
        done = Say("Path update") .set_name("done") .set_parent(self)
        
        successtrans1 = SuccessTrans() .set_name("successtrans1")
        successtrans1 .add_sources(detect) .add_destinations(replan)
        
        failuretrans1 = FailureTrans() .set_name("failuretrans1")
        failuretrans1 .add_sources(detect) .add_destinations(done)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(replan) .add_destinations(done)
        
        return self
