from aim_fsm import *

class FINAL0(StateMachineProgram):
 def setup(self):
     #     	findGoal =S=> computeMid
     # 		findGoal =F=> {failMsg}
     # 		computeMid =S=> turnGoal
     # 		turnGoal =C=> findBall
     #         findBall =F=> {NoBall}
     # 		findBall =S=> driveBall
     # 		driveBall =C=> turnBall
     # 		turnBall =C=> forwardBall
     # 		forwardBall =C=> kickBall
     # 		kickBall =C=> checkGoal
     # 		checkGoal =S=> {scoreMsg}
     #         checkGoal =F=> {missMsg}
     #         scoreMsg =C=> {findGoal}
     #         missMsg =C=>{findGoal}
     # 
     #         findGoal: FindGoalBarrels()
     # 		computeMid: ComputeGoalMidpoint()
     # 		turnGoal: TurnTowardGoal()
     # 		findBall: FindBall()
     # 		driveBall: DriveToBall()
     # 		turnBall: TurnToBall()
     # 		forwardBall: ForwardToBall()
     # 		kickBall: KickBall()
     # 		checkGoal: GoalCheck()
     # 		scoreMsg: Say('GOAL SCORED')
     # 		missMsg: Say('Shot missed')
     # 		failMsg: Say('Could not find goal')
     #         NoBall: Say('Could not find the ball')
     
     # Code generated by genfsm on Thu May 28 10:28:44 2026:
     
     findGoal = FindGoalBarrels() .set_name("findGoal") .set_parent(self)
     computeMid = ComputeGoalMidpoint() .set_name("computeMid") .set_parent(self)
     turnGoal = TurnTowardGoal() .set_name("turnGoal") .set_parent(self)
     findBall = FindBall() .set_name("findBall") .set_parent(self)
     driveBall = DriveToBall() .set_name("driveBall") .set_parent(self)
     turnBall = TurnToBall() .set_name("turnBall") .set_parent(self)
     forwardBall = ForwardToBall() .set_name("forwardBall") .set_parent(self)
     kickBall = KickBall() .set_name("kickBall") .set_parent(self)
     checkGoal = GoalCheck() .set_name("checkGoal") .set_parent(self)
     scoreMsg = Say('GOAL SCORED') .set_name("scoreMsg") .set_parent(self)
     missMsg = Say('Shot missed') .set_name("missMsg") .set_parent(self)
     failMsg = Say('Could not find goal') .set_name("failMsg") .set_parent(self)
     NoBall = Say('Could not find the ball') .set_name("NoBall") .set_parent(self)
     
     successtrans1 = SuccessTrans() .set_name("successtrans1")
     successtrans1 .add_sources(findGoal) .add_destinations(computeMid)
     
     failuretrans1 = FailureTrans() .set_name("failuretrans1")
     failuretrans1 .add_sources(findGoal) .add_destinations(failMsg)
     
     successtrans2 = SuccessTrans() .set_name("successtrans2")
     successtrans2 .add_sources(computeMid) .add_destinations(turnGoal)
     
     completiontrans1 = CompletionTrans() .set_name("completiontrans1")
     completiontrans1 .add_sources(turnGoal) .add_destinations(findBall)
     
     failuretrans2 = FailureTrans() .set_name("failuretrans2")
     failuretrans2 .add_sources(findBall) .add_destinations(NoBall)
     
     successtrans3 = SuccessTrans() .set_name("successtrans3")
     successtrans3 .add_sources(findBall) .add_destinations(driveBall)
     
     completiontrans2 = CompletionTrans() .set_name("completiontrans2")
     completiontrans2 .add_sources(driveBall) .add_destinations(turnBall)
     
     completiontrans3 = CompletionTrans() .set_name("completiontrans3")
     completiontrans3 .add_sources(turnBall) .add_destinations(forwardBall)
     
     completiontrans4 = CompletionTrans() .set_name("completiontrans4")
     completiontrans4 .add_sources(forwardBall) .add_destinations(kickBall)
     
     completiontrans5 = CompletionTrans() .set_name("completiontrans5")
     completiontrans5 .add_sources(kickBall) .add_destinations(checkGoal)
     
     successtrans4 = SuccessTrans() .set_name("successtrans4")
     successtrans4 .add_sources(checkGoal) .add_destinations(scoreMsg)
     
     failuretrans3 = FailureTrans() .set_name("failuretrans3")
     failuretrans3 .add_sources(checkGoal) .add_destinations(missMsg)
     
     completiontrans6 = CompletionTrans() .set_name("completiontrans6")
     completiontrans6 .add_sources(scoreMsg) .add_destinations(findGoal)
     
     completiontrans7 = CompletionTrans() .set_name("completiontrans7")
     completiontrans7 .add_sources(missMsg) .add_destinations(findGoal)
     
     return self

class FindGoalBarrels(StateNode):
	def start(self, event=None):
		super().start(event)
		barrels = []
		for obj in robot.world_map.objects.values():

			if isinstance(obj, BarrelObj) and obj.is_visible:
				barrels.append(obj)

		if len(barrels) >= 2:
			robot.goal_barrel_1 = barrels[0]
			robot.goal_barrel_2 = barrels[1]

			self.post_success()
			return

		self.post_failure()

class ComputeGoalMidpoint(StateNode):
	def start(self, event=None):
		super().start(event)

		barrel1 = robot.goal_barrel_1
		barrel2 = robot.goal_barrel_2

		mid_x = (barrel1.pose.x + barrel2.pose.x) / 2
		mid_y = (barrel1.pose.y + barrel2.pose.y) / 2

		robot.goal_midpoint = (mid_x, mid_y)

		self.post_success()

class TurnTowardGoal(StateNode):
	def start(self, event=None):
		super().start(event)

		goal_x, goal_y = robot.goal_midpoint

		robot_x = robot.pose.x
		robot_y = robot.pose.y

		dist_x = goal_x - robot_x
		dist_y = goal_y - robot_y

		target_heading = degrees(atan2(dist_y, dist_x))

		current_heading = degrees(robot.pose.theta)

		turn_angle = target_heading - current_heading

		while turn_angle > 180:
			turn_angle -= 360

		while turn_angle < -180:
			turn_angle += 360

		self.turn = Turn(turn_angle)

		self.turn.set_parent(self)
		self.turn.start()

	def child_completed(self, child, event):
		self.post_completion()

class FindBall(StateNode):
	def start(self, event=None):
		super().start(event)

		ball = None

		# Search for visible sports ball
		for obj in robot.world_map.objects.values():

			if isinstance(obj, SportsBallObj) and obj.is_visible:

				ball = obj
				break
		if ball is None:

			print("Could not find sports ball")

			self.post_failure()
			return

		robot.target_ball = ball

		self.robot.path_planner.plan_path_this_process(
			self.robot,
			robot.target_ball
		)

		self.robot.rrt.draw_path = self.robot.rrt.path

		self.post_success()

class DriveToBall(StateNode):
    def __init__(self):
        super().__init__(launch_path_viewer = True,
                         launch_particle_viewer = True,
                         speech = False)

    class PathToBall(StateNode):
        def start(self, event=None):
            super().start(event)
            ob = self.robot.world_map.objects['SportsBallObj.a']
            self.robot.path_planner.plan_path_this_process(self.robot, ob)
            self.robot.rrt.draw_path = self.robot.rrt.path
            print(self.robot.rrt.path)

    def setup(self):
        #         TagDetection(enabled=True) =N=> loop
        # 
        #         loop: self.PathToBall() =N=> loop
        
        # Code generated by genfsm on Thu May 28 10:28:44 2026:
        
        tagdetection1 = TagDetection(enabled=True) .set_name("tagdetection1") .set_parent(self)
        loop = self.PathToBall() .set_name("loop") .set_parent(self)
        
        nulltrans1 = NullTrans() .set_name("nulltrans1")
        nulltrans1 .add_sources(tagdetection1) .add_destinations(loop)
        
        nulltrans2 = NullTrans() .set_name("nulltrans2")
        nulltrans2 .add_sources(loop) .add_destinations(loop)
        
        return self

class TurnToBall(StateNode):
	def start(self, event=None):
		super().start(event)

		current_heading = degrees(robot.pose.theta)
		turn_angle = robot.drive_angle - current_heading
		while turn_angle > 180:
			turn_angle -= 360
		while turn_angle < -180:
			turn_angle += 360

		self.turn = Turn(turn_angle)
		self.turn.set_parent(self)
		self.turn.start()

	def child_completed(self, child, event):
		self.post_completion()

class ForwardToBall(StateNode):
	def start(self, event=None):
		super().start(event)

		self.forward = Forward(robot.drive_distance)

		self.forward.set_parent(self)
		self.forward.start()

	def child_completed(self, child, event):
		self.post_completion()

class KickBall(StateNode):
	def start(self, event=None):
		super().start(event)
		self.robot.actuators['kick'].kick(self)
		self.post_completion()

class GoalCheck(StateNode):
	goals_scored = 0
	def start(self, event=None):
		super().start(event)

		ball = None
		for obj in robot.world_map.objects.values():
			if isinstance(obj, SportsBallObj) and obj.is_visible:
				ball = obj
				break

		if ball is None:
			self.post_failure()
			return

		b1 = robot.goal_barrel_1
		b2 = robot.goal_barrel_2

		min_x = min(b1.pose.x, b2.pose.x)
		max_x = max(b1.pose.x, b2.pose.x)

		if (min_x <= ball.pose.x <= max_x):

			GoalCheck.goals_scored += 1

			Say("Goals scored", {GoalCheck.goals_scored})
			print("Goals scored:", GoalCheck.goals_scored)

			self.post_success()
		else:
			self.post_failure()