from aim_fsm import *

class SoccerStartup(StateMachineProgram):
    def setup(self):
        #         scan:ScanEnvironment()
        #         scan =C=> begin
        #         begin: Say("Map Complete")
        
        # Code generated by genfsm on Mon Jun  8 13:21:50 2026:
        
        scan = ScanEnvironment() .set_name("scan") .set_parent(self)
        begin = Say("Map Complete") .set_name("begin") .set_parent(self)
        
        completiontrans1 = CompletionTrans() .set_name("completiontrans1")
        completiontrans1 .add_sources(scan) .add_destinations(begin)
        
        return self

class ScanEnvironment(StateMachineProgram):
    def setup(self):
        #         scan1: Print("45") =N=> Turn(45) =C=> scan2
        #         scan2: Turn(45) =C=> scan3
        #         scan3: Turn(45) =C=> scan4
        #         scan4: Turn(45) =C=> scan5
        #         scan5: Turn(45) =C=> scan6
        #         scan6: Turn(45) =C=> scan7
        #         scan7: Turn(45) =C=> scan8
        #         scan8: Turn(45) =C=> done
        #         done: Say("Map Complete")
        
        # Code generated by genfsm on Mon Jun  8 13:21:50 2026:
        
        scan1 = Print("45") .set_name("scan1") .set_parent(self)
        turn1 = Turn(45) .set_name("turn1") .set_parent(self)
        scan2 = Turn(45) .set_name("scan2") .set_parent(self)
        scan3 = Turn(45) .set_name("scan3") .set_parent(self)
        scan4 = Turn(45) .set_name("scan4") .set_parent(self)
        scan5 = Turn(45) .set_name("scan5") .set_parent(self)
        scan6 = Turn(45) .set_name("scan6") .set_parent(self)
        scan7 = Turn(45) .set_name("scan7") .set_parent(self)
        scan8 = Turn(45) .set_name("scan8") .set_parent(self)
        done = Say("Map Complete") .set_name("done") .set_parent(self)
        
        nulltrans1 = NullTrans() .set_name("nulltrans1")
        nulltrans1 .add_sources(scan1) .add_destinations(turn1)
        
        completiontrans2 = CompletionTrans() .set_name("completiontrans2")
        completiontrans2 .add_sources(turn1) .add_destinations(scan2)
        
        completiontrans3 = CompletionTrans() .set_name("completiontrans3")
        completiontrans3 .add_sources(scan2) .add_destinations(scan3)
        
        completiontrans4 = CompletionTrans() .set_name("completiontrans4")
        completiontrans4 .add_sources(scan3) .add_destinations(scan4)
        
        completiontrans5 = CompletionTrans() .set_name("completiontrans5")
        completiontrans5 .add_sources(scan4) .add_destinations(scan5)
        
        completiontrans6 = CompletionTrans() .set_name("completiontrans6")
        completiontrans6 .add_sources(scan5) .add_destinations(scan6)
        
        completiontrans7 = CompletionTrans() .set_name("completiontrans7")
        completiontrans7 .add_sources(scan6) .add_destinations(scan7)
        
        completiontrans8 = CompletionTrans() .set_name("completiontrans8")
        completiontrans8 .add_sources(scan7) .add_destinations(scan8)
        
        completiontrans9 = CompletionTrans() .set_name("completiontrans9")
        completiontrans9 .add_sources(scan8) .add_destinations(done)
        
        return self
